version: "2"
linters:
  default: all
  disable:
    - depguard
    - errchkjson
    - exhaustruct
    - funlen
    - mnd
    - nilerr
    - nlreturn
    - tagliatelle
    - testpackage
    - wsl
    - wsl_v5
    - noinlineerr
  settings:
    lll:
      line-length: 140
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
    varnamelen:
      min-name-length: 2
      ignore-decls:
        - w http.ResponseWriter
        - i int
        - r *http.Request
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
