# yaml-language-server: $schema=https://github.com/oapi-codegen/oapi-codegen/blob/main/configuration-schema.json
package: oapi
generate:
  std-http-server: true
  embedded-spec: true
  models: true
output: ../../internal/api/oapi/rest.gen.go