//go:build go1.22

// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package oapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// BadRequest defines model for BadRequest.
type BadRequest = string

// Post defines model for Post.
type Post struct {
	// Content Post content
	Content string `json:"content"`
	Id      *int64 `json:"id,omitempty"`

	// Title Short headline of your post
	Title  string `json:"title"`
	UserId int64  `json:"user_id"`
}

// PostInput defines model for PostInput.
type PostInput struct {
	// Content Post content
	Content string `json:"content"`

	// Title Short headline of your post
	Title  string `json:"title"`
	UserId int64  `json:"user_id"`
}

// ResourceNotFound defines model for ResourceNotFound.
type ResourceNotFound = string

// User defines model for User.
type User struct {
	// Email Users email address
	Email string `json:"email"`
	Id    int64  `json:"id"`

	// Name Users full name
	Name string `json:"name"`
}

// UserInput defines model for UserInput.
type UserInput struct {
	// Email Users email address
	Email string `json:"email"`

	// Name Users full name
	Name string `json:"name"`
}

// PostBody defines model for PostBody.
type PostBody = PostInput

// UserBody defines model for UserBody.
type UserBody = UserInput

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = PostInput

// UpdatePostJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody = PostInput

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserInput

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /posts)
	ListPosts(w http.ResponseWriter, r *http.Request)

	// (POST /posts)
	CreatePost(w http.ResponseWriter, r *http.Request)

	// (DELETE /posts/{id})
	DeletePost(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /posts/{id})
	GetPost(w http.ResponseWriter, r *http.Request, id int64)

	// (PUT /posts/{id})
	UpdatePost(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)

	// (POST /users)
	CreateUser(w http.ResponseWriter, r *http.Request)

	// (DELETE /users/{id})
	DeleteUser(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /users/{id})
	GetUser(w http.ResponseWriter, r *http.Request, id int64)

	// (PUT /users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListPosts operation middleware
func (siw *ServerInterfaceWrapper) ListPosts(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPosts(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePost operation middleware
func (siw *ServerInterfaceWrapper) CreatePost(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePost(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeletePost operation middleware
func (siw *ServerInterfaceWrapper) DeletePost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeletePost(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPost operation middleware
func (siw *ServerInterfaceWrapper) GetPost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPost(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdatePost operation middleware
func (siw *ServerInterfaceWrapper) UpdatePost(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdatePost(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteUser operation middleware
func (siw *ServerInterfaceWrapper) DeleteUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/posts", wrapper.ListPosts)
	m.HandleFunc("POST "+options.BaseURL+"/posts", wrapper.CreatePost)
	m.HandleFunc("DELETE "+options.BaseURL+"/posts/{id}", wrapper.DeletePost)
	m.HandleFunc("GET "+options.BaseURL+"/posts/{id}", wrapper.GetPost)
	m.HandleFunc("PUT "+options.BaseURL+"/posts/{id}", wrapper.UpdatePost)
	m.HandleFunc("GET "+options.BaseURL+"/users", wrapper.ListUsers)
	m.HandleFunc("POST "+options.BaseURL+"/users", wrapper.CreateUser)
	m.HandleFunc("DELETE "+options.BaseURL+"/users/{id}", wrapper.DeleteUser)
	m.HandleFunc("GET "+options.BaseURL+"/users/{id}", wrapper.GetUser)
	m.HandleFunc("PUT "+options.BaseURL+"/users/{id}", wrapper.UpdateUser)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xZWW8cuRH+KwUmj70zrWMtp5+S3fUGCpyF4uNpYQQUWTNd3ibZIos6YEx+e1DsOTUt",
	"yzIk2wn81tNVLLK+Or5izwdlguuDR89JNR9UxIuMiX8KlrC8OAvl1408m+AZPcuj7vuOjGYKfvo+BS/v",
	"kmnRaXn6c8SZatSfphvj00GapmLw1PeZ1WKxqMqGFNGqhmPGRaXeJoyPuqEYvHvDRbU0U7z9SdtXAwLy",
	"y+JM545Vo079pe7IgukIPQMVc5Ximx5VoxJH8nO1qApasrKPocfISwy33LCYTKRe3FBNUYeVtFJ4rV3f",
	"icWXIaID6lN2YEMXIiRi0A65Ev2EhpFzBG2pp2TIzwE74goSWrABkHJywQKj60ME8oYs2ewZMkOnz0NE",
	"QB5MIzg99xp0RxdZT+AtA3pyoC04kodL9KRdBReZEviQOGYLeI3REJeAQO467UwYLIsSJZKdiknqAa8B",
	"NZjgXLBhcOAia57AL2JSZ0agmCMufSUPEfuILXqLkQRvuAxd7lkzwqV4CpgSgqGuWyGEgBlmeU6awcuB",
	"oNeRNOc4gRfXBnvGLDB6hmCMRqMZTO7JapYVwUMfA1n0gmIuQQaTu16L3xBmMzKkwWLCKFIXOjmGFoDI",
	"AqYlrtlNVKWcvn6Jfs6tan6s67pSjvzqxdFI3pCV5JiF6LSkG3l+djyYIZedav5yeHh0dHJYHz17/uPx",
	"ycmzlc1BerC2SJ5xjlFMMrGk0u2Ue92GyNCith15hDCDm5Aj9JK4j5CBt5w/vOX74YjvOWH896MDsFPp",
	"vy/RqNSm2FbbvluvDefv0fCqjIeW8b2Wv9fyA2v5e+F9fuG9whRyNPhb4F9D9naXhVdS8IFhVuQjbgnf",
	"79ctOk3dflREOUERgrY2Yko70XgfWv/XPp93ZCYmuI+D/IU6u9cO7/JklrsOisK2F/8IrYd/TeCsOPJQ",
	"J25FlAT11RYF1bFIbqaubyYUXxm3eyATdfKzsH/CNy0l+NvZKUgORG04wRVxCxrOtfkDvQVuNcNVJMYE",
	"0gOBA5D/waEL8QaMNi0muGrJtKAjwhX1KLMsag+5D9KhE+vIE3jTIrx68frNLHewGaWlWfHqEGJgjh6j",
	"ZrQwi8ENMhtMdqXjok9ZEADtZcUPM4qJpdvS3IP2Fv5A7EXOLYIJFqU9647mXtYPvoloZbHwkvS3jgz6",
	"VGI4xFL98/SNdJTYqUa1zH1qptOrq6uJI56gzdP/aCml6cvTn1/89vrFxNmtBq1elzAXf+WcqlKXGNOA",
	"eT2pJweiHHr0uifVqKNJPalVpXrNbcnjqfTu8jTHkYHgV+SCu4aOEguGg36xGYtTp1YaPiU+W0oipl56",
	"fLF6WNcPugQRo0ufcv3aBqGMLXLATSvVMeqbISF3PXolxOPTLX9Ej/U8SY4XNnu3qIaHPUh+jqi5QLKk",
	"vV0kBvHZINrcRG/u8mnnsjpd31QXezgePOrtdQyaYfor5y85dvzA2H1sz61L6cjOpcnKfCQjgrSyK4xS",
	"UcOFNUSYaerQQvldth+L2KJapvP0A9nFELkOeaRf/lLeJylu8pYuyWbdjcdzUF3Hcyckx3dM0MO2SwyP",
	"Hw3DvcHirhhuRovRvL6n0hP5eYcFDTi/gTKC0oww7mHzd+RxYOovk6tLH79NlDfZrJrf9wjb00VGkDFy",
	"F+A1bx8cHZ0ImaqmNOvVuNIMo8vuB6Bqy7W9KW1vtn1XqeVIc+tMvS2N7b6KGPSeoMPVT/V9biR4uTjx",
	"jSaPNDJJjYfw8qA/xstvl5Kn5+Vya9niZfn9ubw8+LMNjrz5JF4uiuO8/HYQPThr1x90n5KXB/j2oSkw",
	"/i/y8jJi63T+TF4ejeeguo7nfbxcMPyKvFz2Hy/6dV5/Gi8XzriXl8eBqb9Mrn41Xv4UlP8feHm0Iga9",
	"J+hw9VP9jTUSvK/Iy/cnT/mjDePlKnc2d/ZmOj04PJmUG3fzvH5eKwnncvno15pN4uSBNcduEltay3vq",
	"u8V/AwAA//80wkG07hwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
